name: Background Process Test

on:
  workflow_dispatch:

jobs:
  test-background:
    runs-on: ubuntu-latest
    steps:
      - name: Background process with sleep
        run: |
          echo "Starting background process..."
          sleep 5 &
          echo "Background process started, PID: $!"
          echo "This should complete after the background process"
          sleep 1
          echo "Foreground process finished, but we should still be waiting for background"

      - name: This step should only run after the background process completes
        run: echo "If you see this, background process handling works!"

  test-multiple-background:
    runs-on: ubuntu-latest
    steps:
      - name: Multiple background processes
        run: |
          echo "Starting multiple background processes"
          sleep 3 &
          echo "Started first background process"
          sleep 6 &
          echo "Started second background process"
          echo "Waiting for all background processes to complete"
          # The workflow should automatically wait for both processes

      - name: Follow-up step
        run: echo "All background processes completed!"
