name: Docker Setup Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Create Docker Network
        run: docker network create app-network

      - name: Start PostgreSQL Container
        run: |
          docker run -d \
            --name postgres \
            --network app-network \
            -p 5432:5432 \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=password \
            -e POSTGRES_DB=testdb \
            postgres:17